version: 2.1

jobs:
  tests:
    docker:
      - image: holochain/holonix:latest
    steps:
      - checkout
      - run:
          no_output_timeout: 20m
          command: nix-shell --run conductor-api-test

workflows:
  version: 2.1
  tests:
    jobs:
      - tests
