name: npm tests

on: [ push, pull_request ]

jobs:
 test:
  runs-on: ${{ matrix.os }}
  strategy:
   matrix:
    os: [
     ubuntu-latest,
     macos-latest
    ]
    node: [ '10', '12', '14' ]
  steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-node@v2-beta
     with:
      node-version: ${{ matrix.node }}
   - uses: actions-rs/toolchain@v1
     with:
      # borrowed from
      # https://github.com/holochain/holochain/blob/6b47b136bc419be6e85000a08a59f67b4c46226c/docs/core_testing.md#requirements
      toolchain: 1.45.2-2020-07-31
      target: wasm32-unknown-unknown
  # todo: this install holochain step can be removed/simplified
  # once holochain/holochain has releases
   - run: ./install-holochain.sh
   - run: ./run-test.sh
   - run: npm run test
